# Generated by Django 3.1.5 on 2021-02-09 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210209_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='likedPosts',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likedPosts', to='network.post'),
        ),
    ]
