# Generated by Django 3.1.5 on 2021-02-09 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likedPosts',
        ),
    ]
