# Generated by Django 3.1.5 on 2021-02-10 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20210210_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowing',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='followInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow', to='network.userfollowing'),
        ),
    ]
