# Generated by Django 3.1.5 on 2021-02-10 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_auto_20210210_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followInfo',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='userFollower',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='userFollowing',
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='followingUserId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
