# Generated by Django 3.1.5 on 2021-01-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210127_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.ImageField(blank=True, max_length=1500, upload_to=''),
        ),
    ]
