# Generated by Django 3.1.5 on 2021-01-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210127_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
