# Generated by Django 3.1.5 on 2021-01-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210127_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
