# Generated by Django 3.1.5 on 2021-01-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210128_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='interested', to='auctions.Listing'),
        ),
    ]
