# Generated by Django 3.1.5 on 2021-01-28 23:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bidUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='currentBid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='currentBid', to='auctions.bid'),
        ),
    ]
