# Generated by Django 3.1.5 on 2021-01-28 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210128_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='currentBid',
        ),
    ]
