# Generated by Django 3.1.5 on 2021-01-29 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20210129_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='Listingbids',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listing'),
        ),
    ]
