# Generated by Django 3.1.5 on 2021-02-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('imgUrl', models.URLField(default='https://sainfoinc.com/wp-content/uploads/2018/02/image-not-available.jpg', max_length=1500)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='recommended',
            field=models.ManyToManyField(blank=True, related_name='recommended', to='movies.Movie'),
        ),
    ]
