# Generated by Django 3.1.5 on 2021-02-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210220_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imbdID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
